/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Classes.Metodos;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author danie
 */
public class Registrarse extends javax.swing.JFrame {

    InicioSeccion inicio = new InicioSeccion();
    Metodos met = new Metodos();
    String rutaImagen = "";
    int mouseX;
    int mouseY;

    public Registrarse() {
        initComponents();

        jLabel8.setForeground(Color.decode("#00678e"));
        jLabel7.setForeground(Color.decode("#00678e"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        IconCerrar = new javax.swing.JLabel();
        Regresar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JTextField();
        Cedula1 = new javax.swing.JTextField();
        Usuario1 = new javax.swing.JTextField();
        Contra = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BottonRegistrar = new rsbuttom.RSButtonMetro();
        VerificarContra1 = new javax.swing.JPasswordField();
        BottonIngresarFoto = new rsbuttom.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        Foto1 = new javax.swing.JLabel();

        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cedula", "NickName", "Pasword", "Foto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jFrame1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 87, 116));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new java.awt.BorderLayout());

        IconCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cruz.png"))); // NOI18N
        IconCerrar.setToolTipText("");
        IconCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconCerrarMouseClicked(evt);
            }
        });
        jPanel2.add(IconCerrar, java.awt.BorderLayout.LINE_END);

        Regresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Entypo_e712(0)_42.png"))); // NOI18N
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        jPanel2.add(Regresar, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 103, 142));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 40, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cedula: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nickname: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 40, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 40, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Verificar contraseña: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 40, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        Nombre1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 2, 0, 31);
        jPanel1.add(Nombre1, gridBagConstraints);

        Cedula1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cedula1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cedula1KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 2, 0, 31);
        jPanel1.add(Cedula1, gridBagConstraints);

        Usuario1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 2, 0, 31);
        jPanel1.add(Usuario1, gridBagConstraints);

        Contra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 2, 0, 31);
        jPanel1.add(Contra, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Las contraseñas no son iguales.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("El campo de la cedula es un campo de solo numeros.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 29;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 0, 31);
        jPanel1.add(jLabel8, gridBagConstraints);

        BottonRegistrar.setText("Registrar");
        BottonRegistrar.setColorHover(new java.awt.Color(101, 203, 255));
        BottonRegistrar.setColorNormal(new java.awt.Color(53, 188, 255));
        BottonRegistrar.setColorPressed(new java.awt.Color(0, 159, 239));
        BottonRegistrar.setMaximumSize(new java.awt.Dimension(180, 30));
        BottonRegistrar.setMinimumSize(new java.awt.Dimension(180, 30));
        BottonRegistrar.setPreferredSize(new java.awt.Dimension(180, 30));
        BottonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 2, 43, 0);
        jPanel1.add(BottonRegistrar, gridBagConstraints);

        VerificarContra1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VerificarContra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VerificarContra1KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 2, 0, 31);
        jPanel1.add(VerificarContra1, gridBagConstraints);

        BottonIngresarFoto.setText("Ingresar foto de perfil");
        BottonIngresarFoto.setColorHover(new java.awt.Color(101, 203, 255));
        BottonIngresarFoto.setColorNormal(new java.awt.Color(53, 188, 255));
        BottonIngresarFoto.setColorPressed(new java.awt.Color(0, 159, 239));
        BottonIngresarFoto.setMaximumSize(new java.awt.Dimension(180, 31));
        BottonIngresarFoto.setMinimumSize(new java.awt.Dimension(180, 31));
        BottonIngresarFoto.setPreferredSize(new java.awt.Dimension(180, 30));
        BottonIngresarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonIngresarFotoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 10, 0, 0);
        jPanel1.add(BottonIngresarFoto, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(23, 158, 224));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Foto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil Blanco.png"))); // NOI18N
        Foto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel3.add(Foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IconCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconCerrarMouseClicked
        dispose();
        this.setVisible(false);
        InicioSeccion ini = new InicioSeccion();
        ini.setVisible(true);
    }//GEN-LAST:event_IconCerrarMouseClicked

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        this.setVisible(false);
        InicioSeccion ini = new InicioSeccion();
        ini.setVisible(true);
    }//GEN-LAST:event_RegresarMouseClicked

    private void BottonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonRegistrarActionPerformed
        if (met.confNum(this.Cedula1.getText())) {
            if (Contra.getText().equals(VerificarContra1.getText())) {
                Object foto2 = "";
                if (!this.rutaImagen.equals("")) {
                    foto2 = this.rutaImagen;
                } else {
                    foto2 = "$";
                }
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                String Nombre2 = this.Nombre1.getText();
                int Cedula2 = Integer.parseInt(this.Cedula1.getText());
                String NickName2 = this.Usuario1.getText();
                Object Pasword2 = this.Contra.getText();
                model.addRow(new Object[]{Nombre2, Cedula2, NickName2, Pasword2, foto2});

                try (BufferedWriter bw = new BufferedWriter(new FileWriter("Usuario.txt", true))) {
                    int filas = jTable1.getRowCount();
                    for (int i = 0; i < filas; i++) {
                        Object Nombre = model.getValueAt(i, 0);
                        Object Cedula = model.getValueAt(i, 1);
                        Object NickName = model.getValueAt(i, 2);
                        Object Pasword = model.getValueAt(i, 3);
                        Object Foto = model.getValueAt(i, 4);
                        bw.write(Nombre + "," + Cedula + "," + NickName + "," + Pasword + "," + Foto);
                        bw.newLine();
                    }
                } catch (Exception e) {
                }
                this.setVisible(false);
                Nombre1.setText("");
                Cedula1.setText("");
                Usuario1.setText("");
                Contra.setText("");
                VerificarContra1.setText("");
                JOptionPane.showMessageDialog(this, "Registro Exitoso.", "Notificacion.", JOptionPane.INFORMATION_MESSAGE);
                inicio.setVisible(true);
                File Pro = new File("Profesor");
                if (!Pro.exists()) {
                    Pro.mkdirs();
                }
                File f = new File("Profesor/" + NickName2);
                f.mkdir();
                File F = new File("Profesor/" + NickName2 + "/Asignatura.txt");
                try {
                    F.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                Nombre1.setText("");
                Cedula1.setText("");
                Usuario1.setText("");
                Contra.setText("");
                VerificarContra1.setText("");
                JOptionPane.showMessageDialog(this, "Contraseñas Diferentes.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            Cedula1.setText("");
            JOptionPane.showMessageDialog(this, "Campo de cedula numerico.", "Error!", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BottonRegistrarActionPerformed

    private void BottonIngresarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonIngresarFotoActionPerformed
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(null);
        archivo.setDialogTitle("Abrir archivo");
        File ruta = new File("C:\\Users\\elspo\\Downloads");
        archivo.setCurrentDirectory(ruta);
        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            File file = archivo.getSelectedFile();
            this.rutaImagen = String.valueOf(file);
            Image foto = getToolkit().getImage(this.rutaImagen);
            foto = foto.getScaledInstance(Foto1.getWidth(), Foto1.getHeight(), Image.SCALE_DEFAULT);
            Foto1.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_BottonIngresarFotoActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void VerificarContra1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VerificarContra1KeyReleased
        if (this.Contra.getText().equals(this.VerificarContra1.getText())) {
            this.jLabel7.setForeground(Color.decode("#00678e"));
        } else {
            this.jLabel7.setForeground(Color.decode("#FFCC00"));
        }
    }//GEN-LAST:event_VerificarContra1KeyReleased

    private void Cedula1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cedula1KeyReleased
        if (met.confNum(this.Cedula1.getText())) {
            this.jLabel8.setForeground(Color.decode("#00678e"));
        } else {
            this.jLabel8.setForeground(Color.decode("#FFCC00"));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula1KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro BottonIngresarFoto;
    private rsbuttom.RSButtonMetro BottonRegistrar;
    private javax.swing.JTextField Cedula1;
    private javax.swing.JPasswordField Contra;
    private javax.swing.JLabel Foto1;
    private javax.swing.JLabel IconCerrar;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JLabel Regresar;
    private javax.swing.JTextField Usuario1;
    private javax.swing.JPasswordField VerificarContra1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
